insert into states (id, shortname, name) values (0, '--', 'Not Set');
insert into states (id, shortname, name) values (1, 'LA', 'Louisiana');
insert into states (id, shortname, name) values (2, 'OH', 'Ohio');
insert into states (id, shortname, name) values (3, 'DC', 'District of Columbia');
insert into states (id, shortname, name) values (4, 'LA', 'Louisiana');
insert into states (id, shortname, name) values (5, 'CA', 'California');
insert into states (id, shortname, name) values (6, 'DC', 'District of Columbia');
insert into states (id, shortname, name) values (7, 'CA', 'California');
insert into states (id, shortname, name) values (8, 'OH', 'Ohio');
insert into states (id, shortname, name) values (9, 'CA', 'California');
insert into states (id, shortname, name) values (10, 'OR', 'Oregon');
insert into states (id, shortname, name) values (11, 'AZ', 'Arizona');
insert into states (id, shortname, name) values (12, 'MI', 'Michigan');
insert into states (id, shortname, name) values (13, 'IN', 'Indiana');
insert into states (id, shortname, name) values (14, 'TX', 'Texas');
insert into states (id, shortname, name) values (15, 'IA', 'Iowa');
insert into states (id, shortname, name) values (16, 'FL', 'Florida');
insert into states (id, shortname, name) values (17, 'AZ', 'Arizona');
insert into states (id, shortname, name) values (18, 'FL', 'Florida');
insert into states (id, shortname, name) values (19, 'SC', 'South Carolina');
insert into states (id, shortname, name) values (20, 'FL', 'Florida');
insert into states (id, shortname, name) values (21, 'ID', 'Idaho');
insert into states (id, shortname, name) values (22, 'PA', 'Pennsylvania');
insert into states (id, shortname, name) values (23, 'HI', 'Hawaii');
insert into states (id, shortname, name) values (24, 'MO', 'Missouri');
insert into states (id, shortname, name) values (25, 'TN', 'Tennessee');
insert into states (id, shortname, name) values (26, 'CT', 'Connecticut');
insert into states (id, shortname, name) values (27, 'HI', 'Hawaii');
insert into states (id, shortname, name) values (28, 'VA', 'Virginia');
insert into states (id, shortname, name) values (29, 'IN', 'Indiana');
insert into states (id, shortname, name) values (30, 'FL', 'Florida');
insert into states (id, shortname, name) values (31, 'GA', 'Georgia');
insert into states (id, shortname, name) values (32, 'CA', 'California');
insert into states (id, shortname, name) values (33, 'CA', 'California');
insert into states (id, shortname, name) values (34, 'NY', 'New York');
insert into states (id, shortname, name) values (35, 'IN', 'Indiana');
insert into states (id, shortname, name) values (36, 'IN', 'Indiana');
insert into states (id, shortname, name) values (37, 'OH', 'Ohio');
insert into states (id, shortname, name) values (38, 'MO', 'Missouri');
insert into states (id, shortname, name) values (39, 'TX', 'Texas');
insert into states (id, shortname, name) values (40, 'OK', 'Oklahoma');
insert into states (id, shortname, name) values (41, 'NV', 'Nevada');
insert into states (id, shortname, name) values (42, 'FL', 'Florida');
insert into states (id, shortname, name) values (43, 'CA', 'California');
insert into states (id, shortname, name) values (44, 'IA', 'Iowa');
insert into states (id, shortname, name) values (45, 'FL', 'Florida');
insert into states (id, shortname, name) values (46, 'AR', 'Arkansas');
insert into states (id, shortname, name) values (47, 'MN', 'Minnesota');
insert into states (id, shortname, name) values (48, 'AK', 'Alaska');
insert into states (id, shortname, name) values (49, 'KY', 'Kentucky');
insert into states (id, shortname, name) values (50, 'AL', 'Alabama');
insert into states (id, shortname, name) values (51, 'KS', 'Kansas');
insert into states (id, shortname, name) values (52, 'TX', 'Texas');
insert into states (id, shortname, name) values (53, 'FL', 'Florida');
insert into states (id, shortname, name) values (54, 'GA', 'Georgia');
insert into states (id, shortname, name) values (55, 'TX', 'Texas');
insert into states (id, shortname, name) values (56, 'AL', 'Alabama');
insert into states (id, shortname, name) values (57, 'CA', 'California');
insert into states (id, shortname, name) values (58, 'AK', 'Alaska');
insert into states (id, shortname, name) values (59, 'NY', 'New York');
insert into states (id, shortname, name) values (60, 'KY', 'Kentucky');
insert into states (id, shortname, name) values (61, 'DC', 'District of Columbia');
insert into states (id, shortname, name) values (62, 'NY', 'New York');
insert into states (id, shortname, name) values (63, 'NC', 'North Carolina');
insert into states (id, shortname, name) values (64, 'NC', 'North Carolina');
insert into states (id, shortname, name) values (65, 'CA', 'California');
insert into states (id, shortname, name) values (66, 'NC', 'North Carolina');
insert into states (id, shortname, name) values (67, 'NY', 'New York');
insert into states (id, shortname, name) values (68, 'AL', 'Alabama');
insert into states (id, shortname, name) values (69, 'NY', 'New York');
insert into states (id, shortname, name) values (70, 'TX', 'Texas');
insert into states (id, shortname, name) values (71, 'CA', 'California');
insert into states (id, shortname, name) values (72, 'CA', 'California');
insert into states (id, shortname, name) values (73, 'IL', 'Illinois');
insert into states (id, shortname, name) values (74, 'OH', 'Ohio');
insert into states (id, shortname, name) values (75, 'TX', 'Texas');
insert into states (id, shortname, name) values (76, 'AK', 'Alaska');
insert into states (id, shortname, name) values (77, 'OH', 'Ohio');
insert into states (id, shortname, name) values (78, 'DC', 'District of Columbia');
insert into states (id, shortname, name) values (79, 'TX', 'Texas');
insert into states (id, shortname, name) values (80, 'KS', 'Kansas');
insert into states (id, shortname, name) values (81, 'LA', 'Louisiana');
insert into states (id, shortname, name) values (82, 'NY', 'New York');
insert into states (id, shortname, name) values (83, 'AZ', 'Arizona');
insert into states (id, shortname, name) values (84, 'IN', 'Indiana');
insert into states (id, shortname, name) values (85, 'CT', 'Connecticut');
insert into states (id, shortname, name) values (86, 'OH', 'Ohio');
insert into states (id, shortname, name) values (87, 'CA', 'California');
insert into states (id, shortname, name) values (88, 'LA', 'Louisiana');
insert into states (id, shortname, name) values (89, 'TX', 'Texas');
insert into states (id, shortname, name) values (90, 'IN', 'Indiana');
insert into states (id, shortname, name) values (91, 'TX', 'Texas');
insert into states (id, shortname, name) values (92, 'CO', 'Colorado');
insert into states (id, shortname, name) values (93, 'MS', 'Mississippi');
insert into states (id, shortname, name) values (94, 'LA', 'Louisiana');
insert into states (id, shortname, name) values (95, 'TX', 'Texas');
insert into states (id, shortname, name) values (96, 'CA', 'California');
insert into states (id, shortname, name) values (97, 'CA', 'California');
insert into states (id, shortname, name) values (98, 'NV', 'Nevada');
insert into states (id, shortname, name) values (99, 'AL', 'Alabama');
insert into states (id, shortname, name) values (100, 'WI', 'Wisconsin');
insert into states (id, shortname, name) values (101, 'KS', 'Kansas');
insert into states (id, shortname, name) values (102, 'NH', 'New Hampshire');
insert into states (id, shortname, name) values (103, 'DC', 'District of Columbia');
insert into states (id, shortname, name) values (104, 'NV', 'Nevada');
insert into states (id, shortname, name) values (105, 'NY', 'New York');
insert into states (id, shortname, name) values (106, 'OH', 'Ohio');
insert into states (id, shortname, name) values (107, 'OH', 'Ohio');
insert into states (id, shortname, name) values (108, 'LA', 'Louisiana');
insert into states (id, shortname, name) values (109, 'OH', 'Ohio');
insert into states (id, shortname, name) values (110, 'CA', 'California');
insert into states (id, shortname, name) values (111, 'NY', 'New York');
insert into states (id, shortname, name) values (112, 'IN', 'Indiana');
insert into states (id, shortname, name) values (113, 'AL', 'Alabama');
insert into states (id, shortname, name) values (114, 'MN', 'Minnesota');
insert into states (id, shortname, name) values (115, 'TX', 'Texas');
insert into states (id, shortname, name) values (116, 'MO', 'Missouri');
insert into states (id, shortname, name) values (117, 'MA', 'Massachusetts');
insert into states (id, shortname, name) values (118, 'OR', 'Oregon');
insert into states (id, shortname, name) values (119, 'TX', 'Texas');
insert into states (id, shortname, name) values (120, 'FL', 'Florida');
insert into states (id, shortname, name) values (121, 'TN', 'Tennessee');
insert into states (id, shortname, name) values (122, 'MA', 'Massachusetts');
insert into states (id, shortname, name) values (123, 'CA', 'California');
insert into states (id, shortname, name) values (124, 'GA', 'Georgia');
insert into states (id, shortname, name) values (125, 'KS', 'Kansas');
insert into states (id, shortname, name) values (126, 'IN', 'Indiana');
insert into states (id, shortname, name) values (127, 'MN', 'Minnesota');
insert into states (id, shortname, name) values (128, 'OH', 'Ohio');
insert into states (id, shortname, name) values (129, 'OH', 'Ohio');
insert into states (id, shortname, name) values (130, 'PA', 'Pennsylvania');
insert into states (id, shortname, name) values (131, 'TX', 'Texas');
insert into states (id, shortname, name) values (132, 'MA', 'Massachusetts');
insert into states (id, shortname, name) values (133, 'OH', 'Ohio');
insert into states (id, shortname, name) values (134, 'VA', 'Virginia');
insert into states (id, shortname, name) values (135, 'DC', 'District of Columbia');
insert into states (id, shortname, name) values (136, 'MI', 'Michigan');
insert into states (id, shortname, name) values (137, 'KY', 'Kentucky');
insert into states (id, shortname, name) values (138, 'NY', 'New York');
insert into states (id, shortname, name) values (139, 'LA', 'Louisiana');
insert into states (id, shortname, name) values (140, 'AL', 'Alabama');
insert into states (id, shortname, name) values (141, 'CA', 'California');
insert into states (id, shortname, name) values (142, 'TX', 'Texas');
insert into states (id, shortname, name) values (143, 'KS', 'Kansas');
insert into states (id, shortname, name) values (144, 'NY', 'New York');
insert into states (id, shortname, name) values (145, 'FL', 'Florida');
insert into states (id, shortname, name) values (146, 'LA', 'Louisiana');
insert into states (id, shortname, name) values (147, 'FL', 'Florida');
insert into states (id, shortname, name) values (148, 'TX', 'Texas');
insert into states (id, shortname, name) values (149, 'KS', 'Kansas');
insert into states (id, shortname, name) values (150, 'VA', 'Virginia');
insert into states (id, shortname, name) values (151, 'TX', 'Texas');
insert into states (id, shortname, name) values (152, 'CT', 'Connecticut');
insert into states (id, shortname, name) values (153, 'AZ', 'Arizona');
insert into states (id, shortname, name) values (154, 'OH', 'Ohio');
insert into states (id, shortname, name) values (155, 'MD', 'Maryland');
insert into states (id, shortname, name) values (156, 'NC', 'North Carolina');
insert into states (id, shortname, name) values (157, 'FL', 'Florida');
insert into states (id, shortname, name) values (158, 'TX', 'Texas');
insert into states (id, shortname, name) values (159, 'NM', 'New Mexico');
insert into states (id, shortname, name) values (160, 'FL', 'Florida');
insert into states (id, shortname, name) values (161, 'CA', 'California');
insert into states (id, shortname, name) values (162, 'NM', 'New Mexico');
insert into states (id, shortname, name) values (163, 'FL', 'Florida');
insert into states (id, shortname, name) values (164, 'MI', 'Michigan');
insert into states (id, shortname, name) values (165, 'CA', 'California');
insert into states (id, shortname, name) values (166, 'SD', 'South Dakota');
insert into states (id, shortname, name) values (167, 'DE', 'Delaware');
insert into states (id, shortname, name) values (168, 'AZ', 'Arizona');
insert into states (id, shortname, name) values (169, 'WI', 'Wisconsin');
insert into states (id, shortname, name) values (170, 'OH', 'Ohio');
insert into states (id, shortname, name) values (171, 'AL', 'Alabama');
insert into states (id, shortname, name) values (172, 'CO', 'Colorado');
insert into states (id, shortname, name) values (173, 'CA', 'California');
insert into states (id, shortname, name) values (174, 'OH', 'Ohio');
insert into states (id, shortname, name) values (175, 'NE', 'Nebraska');
insert into states (id, shortname, name) values (176, 'KY', 'Kentucky');
insert into states (id, shortname, name) values (177, 'RI', 'Rhode Island');
insert into states (id, shortname, name) values (178, 'VA', 'Virginia');
insert into states (id, shortname, name) values (179, 'VA', 'Virginia');
insert into states (id, shortname, name) values (180, 'DC', 'District of Columbia');
insert into states (id, shortname, name) values (181, 'MI', 'Michigan');
insert into states (id, shortname, name) values (182, 'TX', 'Texas');
insert into states (id, shortname, name) values (183, 'NC', 'North Carolina');
insert into states (id, shortname, name) values (184, 'NE', 'Nebraska');
insert into states (id, shortname, name) values (185, 'MS', 'Mississippi');
insert into states (id, shortname, name) values (186, 'SC', 'South Carolina');
insert into states (id, shortname, name) values (187, 'TX', 'Texas');
insert into states (id, shortname, name) values (188, 'GA', 'Georgia');
insert into states (id, shortname, name) values (189, 'CA', 'California');
insert into states (id, shortname, name) values (190, 'TX', 'Texas');
insert into states (id, shortname, name) values (191, 'TN', 'Tennessee');
insert into states (id, shortname, name) values (192, 'VA', 'Virginia');
insert into states (id, shortname, name) values (193, 'TX', 'Texas');
insert into states (id, shortname, name) values (194, 'IN', 'Indiana');
insert into states (id, shortname, name) values (195, 'MI', 'Michigan');
insert into states (id, shortname, name) values (196, 'TX', 'Texas');
insert into states (id, shortname, name) values (197, 'NC', 'North Carolina');
insert into states (id, shortname, name) values (198, 'NY', 'New York');
insert into states (id, shortname, name) values (199, 'CA', 'California');
insert into states (id, shortname, name) values (200, 'LA', 'Louisiana');
insert into states (id, shortname, name) values (201, 'PA', 'Pennsylvania');
insert into states (id, shortname, name) values (202, 'OR', 'Oregon');
insert into states (id, shortname, name) values (203, 'MI', 'Michigan');
insert into states (id, shortname, name) values (204, 'MA', 'Massachusetts');
insert into states (id, shortname, name) values (205, 'FL', 'Florida');
insert into states (id, shortname, name) values (206, 'CA', 'California');
insert into states (id, shortname, name) values (207, 'WV', 'West Virginia');
insert into states (id, shortname, name) values (208, 'OH', 'Ohio');
insert into states (id, shortname, name) values (209, 'FL', 'Florida');
insert into states (id, shortname, name) values (210, 'NC', 'North Carolina');
insert into states (id, shortname, name) values (211, 'NY', 'New York');
insert into states (id, shortname, name) values (212, 'FL', 'Florida');
insert into states (id, shortname, name) values (213, 'OH', 'Ohio');
insert into states (id, shortname, name) values (214, 'PA', 'Pennsylvania');
insert into states (id, shortname, name) values (215, 'CA', 'California');
insert into states (id, shortname, name) values (216, 'OH', 'Ohio');
insert into states (id, shortname, name) values (217, 'IN', 'Indiana');
insert into states (id, shortname, name) values (218, 'TX', 'Texas');
insert into states (id, shortname, name) values (219, 'AL', 'Alabama');
insert into states (id, shortname, name) values (220, 'MO', 'Missouri');
insert into states (id, shortname, name) values (221, 'VA', 'Virginia');
insert into states (id, shortname, name) values (222, 'CA', 'California');
insert into states (id, shortname, name) values (223, 'TX', 'Texas');
insert into states (id, shortname, name) values (224, 'PA', 'Pennsylvania');
insert into states (id, shortname, name) values (225, 'TX', 'Texas');
insert into states (id, shortname, name) values (226, 'OK', 'Oklahoma');
insert into states (id, shortname, name) values (227, 'TX', 'Texas');
insert into states (id, shortname, name) values (228, 'MN', 'Minnesota');
insert into states (id, shortname, name) values (229, 'CA', 'California');
insert into states (id, shortname, name) values (230, 'FL', 'Florida');
insert into states (id, shortname, name) values (231, 'AZ', 'Arizona');
insert into states (id, shortname, name) values (232, 'UT', 'Utah');
insert into states (id, shortname, name) values (233, 'CO', 'Colorado');
insert into states (id, shortname, name) values (234, 'GA', 'Georgia');
insert into states (id, shortname, name) values (235, 'ND', 'North Dakota');
insert into states (id, shortname, name) values (236, 'CO', 'Colorado');
insert into states (id, shortname, name) values (237, 'MO', 'Missouri');
insert into states (id, shortname, name) values (238, 'PA', 'Pennsylvania');
insert into states (id, shortname, name) values (239, 'WA', 'Washington');
insert into states (id, shortname, name) values (240, 'KS', 'Kansas');
insert into states (id, shortname, name) values (241, 'CA', 'California');
insert into states (id, shortname, name) values (242, 'TX', 'Texas');
insert into states (id, shortname, name) values (243, 'CA', 'California');
insert into states (id, shortname, name) values (244, 'UT', 'Utah');
insert into states (id, shortname, name) values (245, 'CA', 'California');
insert into states (id, shortname, name) values (246, 'IL', 'Illinois');
insert into states (id, shortname, name) values (247, 'TX', 'Texas');
insert into states (id, shortname, name) values (248, 'OH', 'Ohio');
insert into states (id, shortname, name) values (249, 'TX', 'Texas');
insert into states (id, shortname, name) values (250, 'FL', 'Florida');
insert into states (id, shortname, name) values (251, 'LA', 'Louisiana');
insert into states (id, shortname, name) values (252, 'VA', 'Virginia');
insert into states (id, shortname, name) values (253, 'IN', 'Indiana');
insert into states (id, shortname, name) values (254, 'FL', 'Florida');
insert into states (id, shortname, name) values (255, 'MA', 'Massachusetts');
insert into states (id, shortname, name) values (256, 'KS', 'Kansas');
insert into states (id, shortname, name) values (257, 'NC', 'North Carolina');
insert into states (id, shortname, name) values (258, 'OR', 'Oregon');
insert into states (id, shortname, name) values (259, 'MN', 'Minnesota');
insert into states (id, shortname, name) values (260, 'TX', 'Texas');
insert into states (id, shortname, name) values (261, 'NJ', 'New Jersey');
insert into states (id, shortname, name) values (262, 'CO', 'Colorado');
insert into states (id, shortname, name) values (263, 'FL', 'Florida');
insert into states (id, shortname, name) values (264, 'MT', 'Montana');
insert into states (id, shortname, name) values (265, 'TX', 'Texas');
insert into states (id, shortname, name) values (266, 'TN', 'Tennessee');
insert into states (id, shortname, name) values (267, 'AL', 'Alabama');
insert into states (id, shortname, name) values (268, 'AR', 'Arkansas');
insert into states (id, shortname, name) values (269, 'NC', 'North Carolina');
insert into states (id, shortname, name) values (270, 'SD', 'South Dakota');
insert into states (id, shortname, name) values (271, 'TX', 'Texas');
insert into states (id, shortname, name) values (272, 'PA', 'Pennsylvania');
insert into states (id, shortname, name) values (273, 'CA', 'California');
insert into states (id, shortname, name) values (274, 'MD', 'Maryland');
insert into states (id, shortname, name) values (275, 'MO', 'Missouri');
insert into states (id, shortname, name) values (276, 'KY', 'Kentucky');
insert into states (id, shortname, name) values (277, 'AZ', 'Arizona');
insert into states (id, shortname, name) values (278, 'AZ', 'Arizona');
insert into states (id, shortname, name) values (279, 'IL', 'Illinois');
insert into states (id, shortname, name) values (280, 'AR', 'Arkansas');
insert into states (id, shortname, name) values (281, 'TX', 'Texas');
insert into states (id, shortname, name) values (282, 'CA', 'California');
insert into states (id, shortname, name) values (283, 'TX', 'Texas');
insert into states (id, shortname, name) values (284, 'NM', 'New Mexico');
insert into states (id, shortname, name) values (285, 'VA', 'Virginia');
insert into states (id, shortname, name) values (286, 'KY', 'Kentucky');
insert into states (id, shortname, name) values (287, 'TX', 'Texas');
insert into states (id, shortname, name) values (288, 'AZ', 'Arizona');
insert into states (id, shortname, name) values (289, 'LA', 'Louisiana');
insert into states (id, shortname, name) values (290, 'CO', 'Colorado');
insert into states (id, shortname, name) values (291, 'IL', 'Illinois');
insert into states (id, shortname, name) values (292, 'NY', 'New York');
insert into states (id, shortname, name) values (293, 'NJ', 'New Jersey');
insert into states (id, shortname, name) values (294, 'NY', 'New York');
insert into states (id, shortname, name) values (295, 'TX', 'Texas');
insert into states (id, shortname, name) values (296, 'MO', 'Missouri');
insert into states (id, shortname, name) values (297, 'WV', 'West Virginia');
insert into states (id, shortname, name) values (298, 'MS', 'Mississippi');
insert into states (id, shortname, name) values (299, 'NY', 'New York');
insert into states (id, shortname, name) values (300, 'MD', 'Maryland');
insert into states (id, shortname, name) values (301, 'MO', 'Missouri');
insert into states (id, shortname, name) values (302, 'OH', 'Ohio');
insert into states (id, shortname, name) values (303, 'PA', 'Pennsylvania');
insert into states (id, shortname, name) values (304, 'NJ', 'New Jersey');
insert into states (id, shortname, name) values (305, 'KY', 'Kentucky');
insert into states (id, shortname, name) values (306, 'IL', 'Illinois');
insert into states (id, shortname, name) values (307, 'MT', 'Montana');
insert into states (id, shortname, name) values (308, 'IA', 'Iowa');
insert into states (id, shortname, name) values (309, 'AZ', 'Arizona');
insert into states (id, shortname, name) values (310, 'NM', 'New Mexico');
insert into states (id, shortname, name) values (311, 'TX', 'Texas');
insert into states (id, shortname, name) values (312, 'NY', 'New York');
insert into states (id, shortname, name) values (313, 'MO', 'Missouri');
insert into states (id, shortname, name) values (314, 'KS', 'Kansas');
insert into states (id, shortname, name) values (315, 'PA', 'Pennsylvania');
insert into states (id, shortname, name) values (316, 'TN', 'Tennessee');
insert into states (id, shortname, name) values (317, 'OH', 'Ohio');
insert into states (id, shortname, name) values (318, 'NY', 'New York');
insert into states (id, shortname, name) values (319, 'DC', 'District of Columbia');
insert into states (id, shortname, name) values (320, 'AZ', 'Arizona');
insert into states (id, shortname, name) values (321, 'IL', 'Illinois');
insert into states (id, shortname, name) values (322, 'CA', 'California');
insert into states (id, shortname, name) values (323, 'MS', 'Mississippi');
insert into states (id, shortname, name) values (324, 'IN', 'Indiana');
insert into states (id, shortname, name) values (325, 'TX', 'Texas');
insert into states (id, shortname, name) values (326, 'VA', 'Virginia');
insert into states (id, shortname, name) values (327, 'TX', 'Texas');
insert into states (id, shortname, name) values (328, 'PA', 'Pennsylvania');
insert into states (id, shortname, name) values (329, 'KY', 'Kentucky');
insert into states (id, shortname, name) values (330, 'CA', 'California');
insert into states (id, shortname, name) values (331, 'TX', 'Texas');
insert into states (id, shortname, name) values (332, 'TX', 'Texas');
insert into states (id, shortname, name) values (333, 'DC', 'District of Columbia');
insert into states (id, shortname, name) values (334, 'WV', 'West Virginia');
insert into states (id, shortname, name) values (335, 'WA', 'Washington');
insert into states (id, shortname, name) values (336, 'LA', 'Louisiana');
insert into states (id, shortname, name) values (337, 'NM', 'New Mexico');
insert into states (id, shortname, name) values (338, 'WA', 'Washington');
insert into states (id, shortname, name) values (339, 'PA', 'Pennsylvania');
insert into states (id, shortname, name) values (340, 'TX', 'Texas');
insert into states (id, shortname, name) values (341, 'AL', 'Alabama');
insert into states (id, shortname, name) values (342, 'FL', 'Florida');
insert into states (id, shortname, name) values (343, 'TX', 'Texas');
insert into states (id, shortname, name) values (344, 'NY', 'New York');
insert into states (id, shortname, name) values (345, 'VA', 'Virginia');
insert into states (id, shortname, name) values (346, 'FL', 'Florida');
insert into states (id, shortname, name) values (347, 'PA', 'Pennsylvania');
insert into states (id, shortname, name) values (348, 'GA', 'Georgia');
insert into states (id, shortname, name) values (349, 'MN', 'Minnesota');
insert into states (id, shortname, name) values (350, 'NY', 'New York');
insert into states (id, shortname, name) values (351, 'NY', 'New York');
insert into states (id, shortname, name) values (352, 'TX', 'Texas');
insert into states (id, shortname, name) values (353, 'KY', 'Kentucky');
insert into states (id, shortname, name) values (354, 'LA', 'Louisiana');
insert into states (id, shortname, name) values (355, 'FL', 'Florida');
insert into states (id, shortname, name) values (356, 'IA', 'Iowa');
insert into states (id, shortname, name) values (357, 'MT', 'Montana');
insert into states (id, shortname, name) values (358, 'CO', 'Colorado');
insert into states (id, shortname, name) values (359, 'MS', 'Mississippi');
insert into states (id, shortname, name) values (360, 'CA', 'California');
insert into states (id, shortname, name) values (361, 'VA', 'Virginia');
insert into states (id, shortname, name) values (362, 'WA', 'Washington');
insert into states (id, shortname, name) values (363, 'DC', 'District of Columbia');
insert into states (id, shortname, name) values (364, 'CO', 'Colorado');
insert into states (id, shortname, name) values (365, 'IL', 'Illinois');
insert into states (id, shortname, name) values (366, 'TX', 'Texas');
insert into states (id, shortname, name) values (367, 'LA', 'Louisiana');
insert into states (id, shortname, name) values (368, 'NJ', 'New Jersey');
insert into states (id, shortname, name) values (369, 'CA', 'California');
insert into states (id, shortname, name) values (370, 'NJ', 'New Jersey');
insert into states (id, shortname, name) values (371, 'IL', 'Illinois');
insert into states (id, shortname, name) values (372, 'PA', 'Pennsylvania');
insert into states (id, shortname, name) values (373, 'FL', 'Florida');
insert into states (id, shortname, name) values (374, 'VA', 'Virginia');
insert into states (id, shortname, name) values (375, 'CA', 'California');
insert into states (id, shortname, name) values (376, 'NC', 'North Carolina');
insert into states (id, shortname, name) values (377, 'KS', 'Kansas');
insert into states (id, shortname, name) values (378, 'IL', 'Illinois');
insert into states (id, shortname, name) values (379, 'FL', 'Florida');
insert into states (id, shortname, name) values (380, 'FL', 'Florida');
insert into states (id, shortname, name) values (381, 'FL', 'Florida');
insert into states (id, shortname, name) values (382, 'FL', 'Florida');
insert into states (id, shortname, name) values (383, 'NY', 'New York');
insert into states (id, shortname, name) values (384, 'VA', 'Virginia');
insert into states (id, shortname, name) values (385, 'WA', 'Washington');
insert into states (id, shortname, name) values (386, 'AZ', 'Arizona');
insert into states (id, shortname, name) values (387, 'NY', 'New York');
insert into states (id, shortname, name) values (388, 'VA', 'Virginia');
insert into states (id, shortname, name) values (389, 'NY', 'New York');
insert into states (id, shortname, name) values (390, 'FL', 'Florida');
insert into states (id, shortname, name) values (391, 'TX', 'Texas');
insert into states (id, shortname, name) values (392, 'CA', 'California');
insert into states (id, shortname, name) values (393, 'AK', 'Alaska');
insert into states (id, shortname, name) values (394, 'MA', 'Massachusetts');
insert into states (id, shortname, name) values (395, 'SC', 'South Carolina');
insert into states (id, shortname, name) values (396, 'AZ', 'Arizona');
insert into states (id, shortname, name) values (397, 'MN', 'Minnesota');
insert into states (id, shortname, name) values (398, 'FL', 'Florida');
insert into states (id, shortname, name) values (399, 'FL', 'Florida');
insert into states (id, shortname, name) values (400, 'CA', 'California');
insert into states (id, shortname, name) values (401, 'AZ', 'Arizona');
insert into states (id, shortname, name) values (402, 'CA', 'California');
insert into states (id, shortname, name) values (403, 'TX', 'Texas');
insert into states (id, shortname, name) values (404, 'TN', 'Tennessee');
insert into states (id, shortname, name) values (405, 'FL', 'Florida');
insert into states (id, shortname, name) values (406, 'WA', 'Washington');
insert into states (id, shortname, name) values (407, 'TX', 'Texas');
insert into states (id, shortname, name) values (408, 'MI', 'Michigan');
insert into states (id, shortname, name) values (409, 'PA', 'Pennsylvania');
insert into states (id, shortname, name) values (410, 'VA', 'Virginia');
insert into states (id, shortname, name) values (411, 'AR', 'Arkansas');
insert into states (id, shortname, name) values (412, 'DC', 'District of Columbia');
insert into states (id, shortname, name) values (413, 'OH', 'Ohio');
insert into states (id, shortname, name) values (414, 'FL', 'Florida');
insert into states (id, shortname, name) values (415, 'CA', 'California');
insert into states (id, shortname, name) values (416, 'VA', 'Virginia');
insert into states (id, shortname, name) values (417, 'VA', 'Virginia');
insert into states (id, shortname, name) values (418, 'FL', 'Florida');
insert into states (id, shortname, name) values (419, 'GA', 'Georgia');
insert into states (id, shortname, name) values (420, 'CA', 'California');
insert into states (id, shortname, name) values (421, 'PA', 'Pennsylvania');
insert into states (id, shortname, name) values (422, 'TX', 'Texas');
insert into states (id, shortname, name) values (423, 'PA', 'Pennsylvania');
insert into states (id, shortname, name) values (424, 'OK', 'Oklahoma');
insert into states (id, shortname, name) values (425, 'DC', 'District of Columbia');
insert into states (id, shortname, name) values (426, 'TX', 'Texas');
insert into states (id, shortname, name) values (427, 'TX', 'Texas');
insert into states (id, shortname, name) values (428, 'TN', 'Tennessee');
insert into states (id, shortname, name) values (429, 'FL', 'Florida');
insert into states (id, shortname, name) values (430, 'CO', 'Colorado');
insert into states (id, shortname, name) values (431, 'MI', 'Michigan');
insert into states (id, shortname, name) values (432, 'SC', 'South Carolina');
insert into states (id, shortname, name) values (433, 'WI', 'Wisconsin');
insert into states (id, shortname, name) values (434, 'OH', 'Ohio');
insert into states (id, shortname, name) values (435, 'AR', 'Arkansas');
insert into states (id, shortname, name) values (436, 'NV', 'Nevada');
insert into states (id, shortname, name) values (437, 'CA', 'California');
insert into states (id, shortname, name) values (438, 'TX', 'Texas');
insert into states (id, shortname, name) values (439, 'IL', 'Illinois');
insert into states (id, shortname, name) values (440, 'DC', 'District of Columbia');
insert into states (id, shortname, name) values (441, 'TX', 'Texas');
insert into states (id, shortname, name) values (442, 'CA', 'California');
insert into states (id, shortname, name) values (443, 'NJ', 'New Jersey');
insert into states (id, shortname, name) values (444, 'TX', 'Texas');
insert into states (id, shortname, name) values (445, 'TX', 'Texas');
insert into states (id, shortname, name) values (446, 'IA', 'Iowa');
insert into states (id, shortname, name) values (447, 'CA', 'California');
insert into states (id, shortname, name) values (448, 'MS', 'Mississippi');
insert into states (id, shortname, name) values (449, 'FL', 'Florida');
insert into states (id, shortname, name) values (450, 'VA', 'Virginia');
insert into states (id, shortname, name) values (451, 'FL', 'Florida');
insert into states (id, shortname, name) values (452, 'VA', 'Virginia');
insert into states (id, shortname, name) values (453, 'OK', 'Oklahoma');
insert into states (id, shortname, name) values (454, 'TX', 'Texas');
insert into states (id, shortname, name) values (455, 'MO', 'Missouri');
insert into states (id, shortname, name) values (456, 'AZ', 'Arizona');
insert into states (id, shortname, name) values (457, 'VA', 'Virginia');
insert into states (id, shortname, name) values (458, 'FL', 'Florida');
insert into states (id, shortname, name) values (459, 'PA', 'Pennsylvania');
insert into states (id, shortname, name) values (460, 'CO', 'Colorado');
insert into states (id, shortname, name) values (461, 'FL', 'Florida');
insert into states (id, shortname, name) values (462, 'FL', 'Florida');
insert into states (id, shortname, name) values (463, 'CT', 'Connecticut');
insert into states (id, shortname, name) values (464, 'NY', 'New York');
insert into states (id, shortname, name) values (465, 'NY', 'New York');
insert into states (id, shortname, name) values (466, 'CA', 'California');
insert into states (id, shortname, name) values (467, 'VA', 'Virginia');
insert into states (id, shortname, name) values (468, 'TX', 'Texas');
insert into states (id, shortname, name) values (469, 'CA', 'California');
insert into states (id, shortname, name) values (470, 'TX', 'Texas');
insert into states (id, shortname, name) values (471, 'FL', 'Florida');
insert into states (id, shortname, name) values (472, 'FL', 'Florida');
insert into states (id, shortname, name) values (473, 'FL', 'Florida');
insert into states (id, shortname, name) values (474, 'IN', 'Indiana');
insert into states (id, shortname, name) values (475, 'CA', 'California');
insert into states (id, shortname, name) values (476, 'LA', 'Louisiana');
insert into states (id, shortname, name) values (477, 'HI', 'Hawaii');
insert into states (id, shortname, name) values (478, 'CA', 'California');
insert into states (id, shortname, name) values (479, 'FL', 'Florida');
insert into states (id, shortname, name) values (480, 'MD', 'Maryland');
insert into states (id, shortname, name) values (481, 'NY', 'New York');
insert into states (id, shortname, name) values (482, 'CA', 'California');
insert into states (id, shortname, name) values (483, 'CA', 'California');
insert into states (id, shortname, name) values (484, 'LA', 'Louisiana');
insert into states (id, shortname, name) values (485, 'PA', 'Pennsylvania');
insert into states (id, shortname, name) values (486, 'HI', 'Hawaii');
insert into states (id, shortname, name) values (487, 'MI', 'Michigan');
insert into states (id, shortname, name) values (488, 'TX', 'Texas');
insert into states (id, shortname, name) values (489, 'TX', 'Texas');
insert into states (id, shortname, name) values (490, 'AZ', 'Arizona');
insert into states (id, shortname, name) values (491, 'AZ', 'Arizona');
insert into states (id, shortname, name) values (492, 'GA', 'Georgia');
insert into states (id, shortname, name) values (493, 'OH', 'Ohio');
insert into states (id, shortname, name) values (494, 'GA', 'Georgia');
insert into states (id, shortname, name) values (495, 'SC', 'South Carolina');
insert into states (id, shortname, name) values (496, 'NY', 'New York');
insert into states (id, shortname, name) values (497, 'TX', 'Texas');
insert into states (id, shortname, name) values (498, 'LA', 'Louisiana');
insert into states (id, shortname, name) values (499, 'NV', 'Nevada');
insert into states (id, shortname, name) values (500, 'TX', 'Texas');
insert into states (id, shortname, name) values (501, 'KY', 'Kentucky');
insert into states (id, shortname, name) values (502, 'VA', 'Virginia');
insert into states (id, shortname, name) values (503, 'FL', 'Florida');
insert into states (id, shortname, name) values (504, 'IL', 'Illinois');
insert into states (id, shortname, name) values (505, 'FL', 'Florida');
insert into states (id, shortname, name) values (506, 'AZ', 'Arizona');
insert into states (id, shortname, name) values (507, 'MI', 'Michigan');
insert into states (id, shortname, name) values (508, 'DC', 'District of Columbia');
insert into states (id, shortname, name) values (509, 'FL', 'Florida');
insert into states (id, shortname, name) values (510, 'TX', 'Texas');
insert into states (id, shortname, name) values (511, 'AL', 'Alabama');
insert into states (id, shortname, name) values (512, 'DC', 'District of Columbia');
insert into states (id, shortname, name) values (513, 'VA', 'Virginia');
insert into states (id, shortname, name) values (514, 'WA', 'Washington');
insert into states (id, shortname, name) values (515, 'CA', 'California');
insert into states (id, shortname, name) values (516, 'CA', 'California');
insert into states (id, shortname, name) values (517, 'CA', 'California');
insert into states (id, shortname, name) values (518, 'OH', 'Ohio');
insert into states (id, shortname, name) values (519, 'TX', 'Texas');
insert into states (id, shortname, name) values (520, 'KY', 'Kentucky');
insert into states (id, shortname, name) values (521, 'IL', 'Illinois');
insert into states (id, shortname, name) values (522, 'WV', 'West Virginia');
insert into states (id, shortname, name) values (523, 'MO', 'Missouri');
insert into states (id, shortname, name) values (524, 'NY', 'New York');
insert into states (id, shortname, name) values (525, 'HI', 'Hawaii');
insert into states (id, shortname, name) values (526, 'FL', 'Florida');
insert into states (id, shortname, name) values (527, 'FL', 'Florida');
insert into states (id, shortname, name) values (528, 'FL', 'Florida');
insert into states (id, shortname, name) values (529, 'TN', 'Tennessee');
insert into states (id, shortname, name) values (530, 'NY', 'New York');
insert into states (id, shortname, name) values (531, 'CA', 'California');
insert into states (id, shortname, name) values (532, 'FL', 'Florida');
insert into states (id, shortname, name) values (533, 'CT', 'Connecticut');
insert into states (id, shortname, name) values (534, 'IL', 'Illinois');
insert into states (id, shortname, name) values (535, 'FL', 'Florida');
insert into states (id, shortname, name) values (536, 'PA', 'Pennsylvania');
insert into states (id, shortname, name) values (537, 'MI', 'Michigan');
insert into states (id, shortname, name) values (538, 'OH', 'Ohio');
insert into states (id, shortname, name) values (539, 'HI', 'Hawaii');
insert into states (id, shortname, name) values (540, 'AK', 'Alaska');
insert into states (id, shortname, name) values (541, 'CA', 'California');
insert into states (id, shortname, name) values (542, 'WI', 'Wisconsin');
insert into states (id, shortname, name) values (543, 'MD', 'Maryland');
insert into states (id, shortname, name) values (544, 'IA', 'Iowa');
insert into states (id, shortname, name) values (545, 'FL', 'Florida');
insert into states (id, shortname, name) values (546, 'CA', 'California');
insert into states (id, shortname, name) values (547, 'CA', 'California');
insert into states (id, shortname, name) values (548, 'AL', 'Alabama');
insert into states (id, shortname, name) values (549, 'VA', 'Virginia');
insert into states (id, shortname, name) values (550, 'NY', 'New York');
insert into states (id, shortname, name) values (551, 'CA', 'California');
insert into states (id, shortname, name) values (552, 'IN', 'Indiana');
insert into states (id, shortname, name) values (553, 'PA', 'Pennsylvania');
insert into states (id, shortname, name) values (554, 'AL', 'Alabama');
insert into states (id, shortname, name) values (555, 'FL', 'Florida');
insert into states (id, shortname, name) values (556, 'MD', 'Maryland');
insert into states (id, shortname, name) values (557, 'FL', 'Florida');
insert into states (id, shortname, name) values (558, 'AZ', 'Arizona');
insert into states (id, shortname, name) values (559, 'FL', 'Florida');
insert into states (id, shortname, name) values (560, 'CA', 'California');
insert into states (id, shortname, name) values (561, 'CA', 'California');
insert into states (id, shortname, name) values (562, 'NY', 'New York');
insert into states (id, shortname, name) values (563, 'CO', 'Colorado');
insert into states (id, shortname, name) values (564, 'AR', 'Arkansas');
insert into states (id, shortname, name) values (565, 'LA', 'Louisiana');
insert into states (id, shortname, name) values (566, 'FL', 'Florida');
insert into states (id, shortname, name) values (567, 'WI', 'Wisconsin');
insert into states (id, shortname, name) values (568, 'CA', 'California');
insert into states (id, shortname, name) values (569, 'OK', 'Oklahoma');
insert into states (id, shortname, name) values (570, 'MA', 'Massachusetts');
insert into states (id, shortname, name) values (571, 'MO', 'Missouri');
insert into states (id, shortname, name) values (572, 'IA', 'Iowa');
insert into states (id, shortname, name) values (573, 'TX', 'Texas');
insert into states (id, shortname, name) values (574, 'CA', 'California');
insert into states (id, shortname, name) values (575, 'FL', 'Florida');
insert into states (id, shortname, name) values (576, 'TX', 'Texas');
insert into states (id, shortname, name) values (577, 'FL', 'Florida');
insert into states (id, shortname, name) values (578, 'FL', 'Florida');
insert into states (id, shortname, name) values (579, 'VA', 'Virginia');
insert into states (id, shortname, name) values (580, 'GA', 'Georgia');
insert into states (id, shortname, name) values (581, 'PA', 'Pennsylvania');
insert into states (id, shortname, name) values (582, 'CO', 'Colorado');
insert into states (id, shortname, name) values (583, 'NV', 'Nevada');
insert into states (id, shortname, name) values (584, 'MD', 'Maryland');
insert into states (id, shortname, name) values (585, 'TX', 'Texas');
insert into states (id, shortname, name) values (586, 'FL', 'Florida');
insert into states (id, shortname, name) values (587, 'CA', 'California');
insert into states (id, shortname, name) values (588, 'WA', 'Washington');
insert into states (id, shortname, name) values (589, 'CA', 'California');
insert into states (id, shortname, name) values (590, 'OH', 'Ohio');
insert into states (id, shortname, name) values (591, 'NC', 'North Carolina');
insert into states (id, shortname, name) values (592, 'NC', 'North Carolina');
insert into states (id, shortname, name) values (593, 'IL', 'Illinois');
insert into states (id, shortname, name) values (594, 'AZ', 'Arizona');
insert into states (id, shortname, name) values (595, 'CA', 'California');
insert into states (id, shortname, name) values (596, 'CA', 'California');
insert into states (id, shortname, name) values (597, 'LA', 'Louisiana');
insert into states (id, shortname, name) values (598, 'TX', 'Texas');
insert into states (id, shortname, name) values (599, 'NC', 'North Carolina');
insert into states (id, shortname, name) values (600, 'NY', 'New York');
insert into states (id, shortname, name) values (601, 'PA', 'Pennsylvania');
insert into states (id, shortname, name) values (602, 'NH', 'New Hampshire');
insert into states (id, shortname, name) values (603, 'LA', 'Louisiana');
insert into states (id, shortname, name) values (604, 'MA', 'Massachusetts');
insert into states (id, shortname, name) values (605, 'FL', 'Florida');
insert into states (id, shortname, name) values (606, 'CA', 'California');
insert into states (id, shortname, name) values (607, 'TX', 'Texas');
insert into states (id, shortname, name) values (608, 'ID', 'Idaho');
insert into states (id, shortname, name) values (609, 'VA', 'Virginia');
insert into states (id, shortname, name) values (610, 'FL', 'Florida');
insert into states (id, shortname, name) values (611, 'MN', 'Minnesota');
insert into states (id, shortname, name) values (612, 'PA', 'Pennsylvania');
insert into states (id, shortname, name) values (613, 'OH', 'Ohio');
insert into states (id, shortname, name) values (614, 'VA', 'Virginia');
insert into states (id, shortname, name) values (615, 'MD', 'Maryland');
insert into states (id, shortname, name) values (616, 'KY', 'Kentucky');
insert into states (id, shortname, name) values (617, 'WA', 'Washington');
insert into states (id, shortname, name) values (618, 'AZ', 'Arizona');
insert into states (id, shortname, name) values (619, 'TN', 'Tennessee');
insert into states (id, shortname, name) values (620, 'CA', 'California');
insert into states (id, shortname, name) values (621, 'TN', 'Tennessee');
insert into states (id, shortname, name) values (622, 'CA', 'California');
insert into states (id, shortname, name) values (623, 'NC', 'North Carolina');
insert into states (id, shortname, name) values (624, 'FL', 'Florida');
insert into states (id, shortname, name) values (625, 'NY', 'New York');
insert into states (id, shortname, name) values (626, 'FL', 'Florida');
insert into states (id, shortname, name) values (627, 'CO', 'Colorado');
insert into states (id, shortname, name) values (628, 'IL', 'Illinois');
insert into states (id, shortname, name) values (629, 'CO', 'Colorado');
insert into states (id, shortname, name) values (630, 'ND', 'North Dakota');
insert into states (id, shortname, name) values (631, 'MT', 'Montana');
insert into states (id, shortname, name) values (632, 'TN', 'Tennessee');
insert into states (id, shortname, name) values (633, 'AR', 'Arkansas');
insert into states (id, shortname, name) values (634, 'OH', 'Ohio');
insert into states (id, shortname, name) values (635, 'AZ', 'Arizona');
insert into states (id, shortname, name) values (636, 'KY', 'Kentucky');
insert into states (id, shortname, name) values (637, 'OH', 'Ohio');
insert into states (id, shortname, name) values (638, 'OK', 'Oklahoma');
insert into states (id, shortname, name) values (639, 'NE', 'Nebraska');
insert into states (id, shortname, name) values (640, 'NY', 'New York');
insert into states (id, shortname, name) values (641, 'AZ', 'Arizona');
insert into states (id, shortname, name) values (642, 'SD', 'South Dakota');
insert into states (id, shortname, name) values (643, 'FL', 'Florida');
insert into states (id, shortname, name) values (644, 'PA', 'Pennsylvania');
insert into states (id, shortname, name) values (645, 'CA', 'California');
insert into states (id, shortname, name) values (646, 'TX', 'Texas');
insert into states (id, shortname, name) values (647, 'AR', 'Arkansas');
insert into states (id, shortname, name) values (648, 'FL', 'Florida');
insert into states (id, shortname, name) values (649, 'MA', 'Massachusetts');
insert into states (id, shortname, name) values (650, 'CA', 'California');
insert into states (id, shortname, name) values (651, 'NC', 'North Carolina');
insert into states (id, shortname, name) values (652, 'OH', 'Ohio');
insert into states (id, shortname, name) values (653, 'FL', 'Florida');
insert into states (id, shortname, name) values (654, 'TN', 'Tennessee');
insert into states (id, shortname, name) values (655, 'NY', 'New York');
insert into states (id, shortname, name) values (656, 'TX', 'Texas');
insert into states (id, shortname, name) values (657, 'TN', 'Tennessee');
insert into states (id, shortname, name) values (658, 'OH', 'Ohio');
insert into states (id, shortname, name) values (659, 'CA', 'California');
insert into states (id, shortname, name) values (660, 'MO', 'Missouri');
insert into states (id, shortname, name) values (661, 'FL', 'Florida');
insert into states (id, shortname, name) values (662, 'IA', 'Iowa');
insert into states (id, shortname, name) values (663, 'MI', 'Michigan');
insert into states (id, shortname, name) values (664, 'MO', 'Missouri');
insert into states (id, shortname, name) values (665, 'CA', 'California');
insert into states (id, shortname, name) values (666, 'NC', 'North Carolina');
insert into states (id, shortname, name) values (667, 'MA', 'Massachusetts');
insert into states (id, shortname, name) values (668, 'PA', 'Pennsylvania');
insert into states (id, shortname, name) values (669, 'OH', 'Ohio');
insert into states (id, shortname, name) values (670, 'NY', 'New York');
insert into states (id, shortname, name) values (671, 'NC', 'North Carolina');
insert into states (id, shortname, name) values (672, 'CA', 'California');
insert into states (id, shortname, name) values (673, 'KS', 'Kansas');
insert into states (id, shortname, name) values (674, 'TX', 'Texas');
insert into states (id, shortname, name) values (675, 'NY', 'New York');
insert into states (id, shortname, name) values (676, 'TX', 'Texas');
insert into states (id, shortname, name) values (677, 'NY', 'New York');
insert into states (id, shortname, name) values (678, 'FL', 'Florida');
insert into states (id, shortname, name) values (679, 'TX', 'Texas');
insert into states (id, shortname, name) values (680, 'NM', 'New Mexico');
insert into states (id, shortname, name) values (681, 'ID', 'Idaho');
insert into states (id, shortname, name) values (682, 'MT', 'Montana');
insert into states (id, shortname, name) values (683, 'FL', 'Florida');
insert into states (id, shortname, name) values (684, 'IN', 'Indiana');
insert into states (id, shortname, name) values (685, 'FL', 'Florida');
insert into states (id, shortname, name) values (686, 'NY', 'New York');
insert into states (id, shortname, name) values (687, 'MO', 'Missouri');
insert into states (id, shortname, name) values (688, 'DC', 'District of Columbia');
insert into states (id, shortname, name) values (689, 'TX', 'Texas');
insert into states (id, shortname, name) values (690, 'TX', 'Texas');
insert into states (id, shortname, name) values (691, 'GA', 'Georgia');
insert into states (id, shortname, name) values (692, 'KS', 'Kansas');
insert into states (id, shortname, name) values (693, 'NC', 'North Carolina');
insert into states (id, shortname, name) values (694, 'NY', 'New York');
insert into states (id, shortname, name) values (695, 'GA', 'Georgia');
insert into states (id, shortname, name) values (696, 'WA', 'Washington');
insert into states (id, shortname, name) values (697, 'NC', 'North Carolina');
insert into states (id, shortname, name) values (698, 'CA', 'California');
insert into states (id, shortname, name) values (699, 'DC', 'District of Columbia');
insert into states (id, shortname, name) values (700, 'PA', 'Pennsylvania');
insert into states (id, shortname, name) values (701, 'KS', 'Kansas');
insert into states (id, shortname, name) values (702, 'MD', 'Maryland');
insert into states (id, shortname, name) values (703, 'TX', 'Texas');
insert into states (id, shortname, name) values (704, 'CA', 'California');
insert into states (id, shortname, name) values (705, 'MO', 'Missouri');
insert into states (id, shortname, name) values (706, 'KY', 'Kentucky');
insert into states (id, shortname, name) values (707, 'CA', 'California');
insert into states (id, shortname, name) values (708, 'WA', 'Washington');
insert into states (id, shortname, name) values (709, 'FL', 'Florida');
insert into states (id, shortname, name) values (710, 'CA', 'California');
insert into states (id, shortname, name) values (711, 'MO', 'Missouri');
insert into states (id, shortname, name) values (712, 'AL', 'Alabama');
insert into states (id, shortname, name) values (713, 'FL', 'Florida');
insert into states (id, shortname, name) values (714, 'DC', 'District of Columbia');
insert into states (id, shortname, name) values (715, 'FL', 'Florida');
insert into states (id, shortname, name) values (716, 'MI', 'Michigan');
insert into states (id, shortname, name) values (717, 'OR', 'Oregon');
insert into states (id, shortname, name) values (718, 'AZ', 'Arizona');
insert into states (id, shortname, name) values (719, 'FL', 'Florida');
insert into states (id, shortname, name) values (720, 'CA', 'California');
insert into states (id, shortname, name) values (721, 'CA', 'California');
insert into states (id, shortname, name) values (722, 'AL', 'Alabama');
insert into states (id, shortname, name) values (723, 'NY', 'New York');
insert into states (id, shortname, name) values (724, 'TN', 'Tennessee');
insert into states (id, shortname, name) values (725, 'HI', 'Hawaii');
insert into states (id, shortname, name) values (726, 'AL', 'Alabama');
insert into states (id, shortname, name) values (727, 'SC', 'South Carolina');
insert into states (id, shortname, name) values (728, 'FL', 'Florida');
insert into states (id, shortname, name) values (729, 'AZ', 'Arizona');
insert into states (id, shortname, name) values (730, 'OR', 'Oregon');
insert into states (id, shortname, name) values (731, 'CA', 'California');
insert into states (id, shortname, name) values (732, 'PA', 'Pennsylvania');
insert into states (id, shortname, name) values (733, 'VA', 'Virginia');
insert into states (id, shortname, name) values (734, 'TX', 'Texas');
insert into states (id, shortname, name) values (735, 'VA', 'Virginia');
insert into states (id, shortname, name) values (736, 'UT', 'Utah');
insert into states (id, shortname, name) values (737, 'MI', 'Michigan');
insert into states (id, shortname, name) values (738, 'WA', 'Washington');
insert into states (id, shortname, name) values (739, 'KS', 'Kansas');
insert into states (id, shortname, name) values (740, 'VA', 'Virginia');
insert into states (id, shortname, name) values (741, 'TX', 'Texas');
insert into states (id, shortname, name) values (742, 'IN', 'Indiana');
insert into states (id, shortname, name) values (743, 'WI', 'Wisconsin');
insert into states (id, shortname, name) values (744, 'TX', 'Texas');
insert into states (id, shortname, name) values (745, 'PA', 'Pennsylvania');
insert into states (id, shortname, name) values (746, 'TX', 'Texas');
insert into states (id, shortname, name) values (747, 'CA', 'California');
insert into states (id, shortname, name) values (748, 'FL', 'Florida');
insert into states (id, shortname, name) values (749, 'AL', 'Alabama');
insert into states (id, shortname, name) values (750, 'CO', 'Colorado');
insert into states (id, shortname, name) values (751, 'LA', 'Louisiana');
insert into states (id, shortname, name) values (752, 'CO', 'Colorado');
insert into states (id, shortname, name) values (753, 'IL', 'Illinois');
insert into states (id, shortname, name) values (754, 'AL', 'Alabama');
insert into states (id, shortname, name) values (755, 'KY', 'Kentucky');
insert into states (id, shortname, name) values (756, 'NC', 'North Carolina');
insert into states (id, shortname, name) values (757, 'MI', 'Michigan');
insert into states (id, shortname, name) values (758, 'IN', 'Indiana');
insert into states (id, shortname, name) values (759, 'CA', 'California');
insert into states (id, shortname, name) values (760, 'NY', 'New York');
insert into states (id, shortname, name) values (761, 'MA', 'Massachusetts');
insert into states (id, shortname, name) values (762, 'ID', 'Idaho');
insert into states (id, shortname, name) values (763, 'IL', 'Illinois');
insert into states (id, shortname, name) values (764, 'WI', 'Wisconsin');
insert into states (id, shortname, name) values (765, 'WV', 'West Virginia');
insert into states (id, shortname, name) values (766, 'IN', 'Indiana');
insert into states (id, shortname, name) values (767, 'IL', 'Illinois');
insert into states (id, shortname, name) values (768, 'LA', 'Louisiana');
insert into states (id, shortname, name) values (769, 'WA', 'Washington');
insert into states (id, shortname, name) values (770, 'TX', 'Texas');
insert into states (id, shortname, name) values (771, 'PA', 'Pennsylvania');
insert into states (id, shortname, name) values (772, 'WA', 'Washington');
insert into states (id, shortname, name) values (773, 'IL', 'Illinois');
insert into states (id, shortname, name) values (774, 'MA', 'Massachusetts');
insert into states (id, shortname, name) values (775, 'IA', 'Iowa');
insert into states (id, shortname, name) values (776, 'IL', 'Illinois');
insert into states (id, shortname, name) values (777, 'VA', 'Virginia');
insert into states (id, shortname, name) values (778, 'OK', 'Oklahoma');
insert into states (id, shortname, name) values (779, 'CA', 'California');
insert into states (id, shortname, name) values (780, 'MN', 'Minnesota');
insert into states (id, shortname, name) values (781, 'OH', 'Ohio');
insert into states (id, shortname, name) values (782, 'TX', 'Texas');
insert into states (id, shortname, name) values (783, 'GA', 'Georgia');
insert into states (id, shortname, name) values (784, 'NY', 'New York');
insert into states (id, shortname, name) values (785, 'PA', 'Pennsylvania');
insert into states (id, shortname, name) values (786, 'IN', 'Indiana');
insert into states (id, shortname, name) values (787, 'TX', 'Texas');
insert into states (id, shortname, name) values (788, 'VA', 'Virginia');
insert into states (id, shortname, name) values (789, 'ID', 'Idaho');
insert into states (id, shortname, name) values (790, 'WA', 'Washington');
insert into states (id, shortname, name) values (791, 'NY', 'New York');
insert into states (id, shortname, name) values (792, 'WI', 'Wisconsin');
insert into states (id, shortname, name) values (793, 'OH', 'Ohio');
insert into states (id, shortname, name) values (794, 'TX', 'Texas');
insert into states (id, shortname, name) values (795, 'CT', 'Connecticut');
insert into states (id, shortname, name) values (796, 'AK', 'Alaska');
insert into states (id, shortname, name) values (797, 'KY', 'Kentucky');
insert into states (id, shortname, name) values (798, 'OH', 'Ohio');
insert into states (id, shortname, name) values (799, 'IA', 'Iowa');
insert into states (id, shortname, name) values (800, 'NY', 'New York');
insert into states (id, shortname, name) values (801, 'MO', 'Missouri');
insert into states (id, shortname, name) values (802, 'IN', 'Indiana');
insert into states (id, shortname, name) values (803, 'MD', 'Maryland');
insert into states (id, shortname, name) values (804, 'AZ', 'Arizona');
insert into states (id, shortname, name) values (805, 'TX', 'Texas');
insert into states (id, shortname, name) values (806, 'TX', 'Texas');
insert into states (id, shortname, name) values (807, 'OR', 'Oregon');
insert into states (id, shortname, name) values (808, 'MA', 'Massachusetts');
insert into states (id, shortname, name) values (809, 'NC', 'North Carolina');
insert into states (id, shortname, name) values (810, 'WI', 'Wisconsin');
insert into states (id, shortname, name) values (811, 'CA', 'California');
insert into states (id, shortname, name) values (812, 'VA', 'Virginia');
insert into states (id, shortname, name) values (813, 'MO', 'Missouri');
insert into states (id, shortname, name) values (814, 'KS', 'Kansas');
insert into states (id, shortname, name) values (815, 'CA', 'California');
insert into states (id, shortname, name) values (816, 'CO', 'Colorado');
insert into states (id, shortname, name) values (817, 'AZ', 'Arizona');
insert into states (id, shortname, name) values (818, 'IN', 'Indiana');
insert into states (id, shortname, name) values (819, 'FL', 'Florida');
insert into states (id, shortname, name) values (820, 'LA', 'Louisiana');
insert into states (id, shortname, name) values (821, 'FL', 'Florida');
insert into states (id, shortname, name) values (822, 'IN', 'Indiana');
insert into states (id, shortname, name) values (823, 'AL', 'Alabama');
insert into states (id, shortname, name) values (824, 'PA', 'Pennsylvania');
insert into states (id, shortname, name) values (825, 'LA', 'Louisiana');
insert into states (id, shortname, name) values (826, 'VA', 'Virginia');
insert into states (id, shortname, name) values (827, 'TX', 'Texas');
insert into states (id, shortname, name) values (828, 'MN', 'Minnesota');
insert into states (id, shortname, name) values (829, 'CA', 'California');
insert into states (id, shortname, name) values (830, 'MI', 'Michigan');
insert into states (id, shortname, name) values (831, 'DC', 'District of Columbia');
insert into states (id, shortname, name) values (832, 'CO', 'Colorado');
insert into states (id, shortname, name) values (833, 'FL', 'Florida');
insert into states (id, shortname, name) values (834, 'AZ', 'Arizona');
insert into states (id, shortname, name) values (835, 'NJ', 'New Jersey');
insert into states (id, shortname, name) values (836, 'DE', 'Delaware');
insert into states (id, shortname, name) values (837, 'NY', 'New York');
insert into states (id, shortname, name) values (838, 'TN', 'Tennessee');
insert into states (id, shortname, name) values (839, 'UT', 'Utah');
insert into states (id, shortname, name) values (840, 'MT', 'Montana');
insert into states (id, shortname, name) values (841, 'IL', 'Illinois');
insert into states (id, shortname, name) values (842, 'NY', 'New York');
insert into states (id, shortname, name) values (843, 'LA', 'Louisiana');
insert into states (id, shortname, name) values (844, 'TX', 'Texas');
insert into states (id, shortname, name) values (845, 'TX', 'Texas');
insert into states (id, shortname, name) values (846, 'MO', 'Missouri');
insert into states (id, shortname, name) values (847, 'RI', 'Rhode Island');
insert into states (id, shortname, name) values (848, 'ND', 'North Dakota');
insert into states (id, shortname, name) values (849, 'NY', 'New York');
insert into states (id, shortname, name) values (850, 'AZ', 'Arizona');
insert into states (id, shortname, name) values (851, 'WV', 'West Virginia');
insert into states (id, shortname, name) values (852, 'DE', 'Delaware');
insert into states (id, shortname, name) values (853, 'CO', 'Colorado');
insert into states (id, shortname, name) values (854, 'TX', 'Texas');
insert into states (id, shortname, name) values (855, 'WA', 'Washington');
insert into states (id, shortname, name) values (856, 'OH', 'Ohio');
insert into states (id, shortname, name) values (857, 'IA', 'Iowa');
insert into states (id, shortname, name) values (858, 'NC', 'North Carolina');
insert into states (id, shortname, name) values (859, 'AL', 'Alabama');
insert into states (id, shortname, name) values (860, 'MN', 'Minnesota');
insert into states (id, shortname, name) values (861, 'KS', 'Kansas');
insert into states (id, shortname, name) values (862, 'TN', 'Tennessee');
insert into states (id, shortname, name) values (863, 'FL', 'Florida');
insert into states (id, shortname, name) values (864, 'LA', 'Louisiana');
insert into states (id, shortname, name) values (865, 'DC', 'District of Columbia');
insert into states (id, shortname, name) values (866, 'TX', 'Texas');
insert into states (id, shortname, name) values (867, 'DC', 'District of Columbia');
insert into states (id, shortname, name) values (868, 'FL', 'Florida');
insert into states (id, shortname, name) values (869, 'TX', 'Texas');
insert into states (id, shortname, name) values (870, 'FL', 'Florida');
insert into states (id, shortname, name) values (871, 'KS', 'Kansas');
insert into states (id, shortname, name) values (872, 'MA', 'Massachusetts');
insert into states (id, shortname, name) values (873, 'CA', 'California');
insert into states (id, shortname, name) values (874, 'TX', 'Texas');
insert into states (id, shortname, name) values (875, 'IL', 'Illinois');
insert into states (id, shortname, name) values (876, 'NY', 'New York');
insert into states (id, shortname, name) values (877, 'DC', 'District of Columbia');
insert into states (id, shortname, name) values (878, 'DC', 'District of Columbia');
insert into states (id, shortname, name) values (879, 'VA', 'Virginia');
insert into states (id, shortname, name) values (880, 'TX', 'Texas');
insert into states (id, shortname, name) values (881, 'FL', 'Florida');
insert into states (id, shortname, name) values (882, 'PA', 'Pennsylvania');
insert into states (id, shortname, name) values (883, 'CT', 'Connecticut');
insert into states (id, shortname, name) values (884, 'TX', 'Texas');
insert into states (id, shortname, name) values (885, 'TN', 'Tennessee');
insert into states (id, shortname, name) values (886, 'VA', 'Virginia');
insert into states (id, shortname, name) values (887, 'NV', 'Nevada');
insert into states (id, shortname, name) values (888, 'MO', 'Missouri');
insert into states (id, shortname, name) values (889, 'IN', 'Indiana');
insert into states (id, shortname, name) values (890, 'TX', 'Texas');
insert into states (id, shortname, name) values (891, 'TX', 'Texas');
insert into states (id, shortname, name) values (892, 'WV', 'West Virginia');
insert into states (id, shortname, name) values (893, 'AK', 'Alaska');
insert into states (id, shortname, name) values (894, 'TX', 'Texas');
insert into states (id, shortname, name) values (895, 'OR', 'Oregon');
insert into states (id, shortname, name) values (896, 'NY', 'New York');
insert into states (id, shortname, name) values (897, 'SC', 'South Carolina');
insert into states (id, shortname, name) values (898, 'TX', 'Texas');
insert into states (id, shortname, name) values (899, 'CA', 'California');
insert into states (id, shortname, name) values (900, 'VA', 'Virginia');
insert into states (id, shortname, name) values (901, 'MI', 'Michigan');
insert into states (id, shortname, name) values (902, 'CA', 'California');
insert into states (id, shortname, name) values (903, 'CA', 'California');
insert into states (id, shortname, name) values (904, 'CT', 'Connecticut');
insert into states (id, shortname, name) values (905, 'OH', 'Ohio');
insert into states (id, shortname, name) values (906, 'AZ', 'Arizona');
insert into states (id, shortname, name) values (907, 'CA', 'California');
insert into states (id, shortname, name) values (908, 'CA', 'California');
insert into states (id, shortname, name) values (909, 'CA', 'California');
insert into states (id, shortname, name) values (910, 'VA', 'Virginia');
insert into states (id, shortname, name) values (911, 'NY', 'New York');
insert into states (id, shortname, name) values (912, 'OH', 'Ohio');
insert into states (id, shortname, name) values (913, 'TX', 'Texas');
insert into states (id, shortname, name) values (914, 'MI', 'Michigan');
insert into states (id, shortname, name) values (915, 'IL', 'Illinois');
insert into states (id, shortname, name) values (916, 'MA', 'Massachusetts');
insert into states (id, shortname, name) values (917, 'TN', 'Tennessee');
insert into states (id, shortname, name) values (918, 'SD', 'South Dakota');
insert into states (id, shortname, name) values (919, 'TN', 'Tennessee');
insert into states (id, shortname, name) values (920, 'TX', 'Texas');
insert into states (id, shortname, name) values (921, 'CA', 'California');
insert into states (id, shortname, name) values (922, 'MI', 'Michigan');
insert into states (id, shortname, name) values (923, 'IL', 'Illinois');
insert into states (id, shortname, name) values (924, 'IA', 'Iowa');
insert into states (id, shortname, name) values (925, 'FL', 'Florida');
insert into states (id, shortname, name) values (926, 'OH', 'Ohio');
insert into states (id, shortname, name) values (927, 'IL', 'Illinois');
insert into states (id, shortname, name) values (928, 'FL', 'Florida');
insert into states (id, shortname, name) values (929, 'VA', 'Virginia');
insert into states (id, shortname, name) values (930, 'SD', 'South Dakota');
insert into states (id, shortname, name) values (931, 'OK', 'Oklahoma');
insert into states (id, shortname, name) values (932, 'MI', 'Michigan');
insert into states (id, shortname, name) values (933, 'AK', 'Alaska');
insert into states (id, shortname, name) values (934, 'OH', 'Ohio');
insert into states (id, shortname, name) values (935, 'TN', 'Tennessee');
insert into states (id, shortname, name) values (936, 'CA', 'California');
insert into states (id, shortname, name) values (937, 'TX', 'Texas');
insert into states (id, shortname, name) values (938, 'MD', 'Maryland');
insert into states (id, shortname, name) values (939, 'PA', 'Pennsylvania');
insert into states (id, shortname, name) values (940, 'UT', 'Utah');
insert into states (id, shortname, name) values (941, 'OK', 'Oklahoma');
insert into states (id, shortname, name) values (942, 'VA', 'Virginia');
insert into states (id, shortname, name) values (943, 'KS', 'Kansas');
insert into states (id, shortname, name) values (944, 'CA', 'California');
insert into states (id, shortname, name) values (945, 'IL', 'Illinois');
insert into states (id, shortname, name) values (946, 'PA', 'Pennsylvania');
insert into states (id, shortname, name) values (947, 'DC', 'District of Columbia');
insert into states (id, shortname, name) values (948, 'TX', 'Texas');
insert into states (id, shortname, name) values (949, 'AZ', 'Arizona');
insert into states (id, shortname, name) values (950, 'NJ', 'New Jersey');
insert into states (id, shortname, name) values (951, 'MO', 'Missouri');
insert into states (id, shortname, name) values (952, 'GA', 'Georgia');
insert into states (id, shortname, name) values (953, 'NC', 'North Carolina');
insert into states (id, shortname, name) values (954, 'NY', 'New York');
insert into states (id, shortname, name) values (955, 'CA', 'California');
insert into states (id, shortname, name) values (956, 'MN', 'Minnesota');
insert into states (id, shortname, name) values (957, 'TN', 'Tennessee');
insert into states (id, shortname, name) values (958, 'MI', 'Michigan');
insert into states (id, shortname, name) values (959, 'VA', 'Virginia');
insert into states (id, shortname, name) values (960, 'NE', 'Nebraska');
insert into states (id, shortname, name) values (961, 'CT', 'Connecticut');
insert into states (id, shortname, name) values (962, 'HI', 'Hawaii');
insert into states (id, shortname, name) values (963, 'GA', 'Georgia');
insert into states (id, shortname, name) values (964, 'PA', 'Pennsylvania');
insert into states (id, shortname, name) values (965, 'NC', 'North Carolina');
insert into states (id, shortname, name) values (966, 'CA', 'California');
insert into states (id, shortname, name) values (967, 'NC', 'North Carolina');
insert into states (id, shortname, name) values (968, 'GA', 'Georgia');
insert into states (id, shortname, name) values (969, 'AZ', 'Arizona');
insert into states (id, shortname, name) values (970, 'NJ', 'New Jersey');
insert into states (id, shortname, name) values (971, 'VA', 'Virginia');
insert into states (id, shortname, name) values (972, 'NC', 'North Carolina');
insert into states (id, shortname, name) values (973, 'IN', 'Indiana');
insert into states (id, shortname, name) values (974, 'CO', 'Colorado');
insert into states (id, shortname, name) values (975, 'CA', 'California');
insert into states (id, shortname, name) values (976, 'IL', 'Illinois');
insert into states (id, shortname, name) values (977, 'CA', 'California');
insert into states (id, shortname, name) values (978, 'CA', 'California');
insert into states (id, shortname, name) values (979, 'MO', 'Missouri');
insert into states (id, shortname, name) values (980, 'IN', 'Indiana');
insert into states (id, shortname, name) values (981, 'CA', 'California');
insert into states (id, shortname, name) values (982, 'IL', 'Illinois');
insert into states (id, shortname, name) values (983, 'NY', 'New York');
insert into states (id, shortname, name) values (984, 'KY', 'Kentucky');
insert into states (id, shortname, name) values (985, 'AZ', 'Arizona');
insert into states (id, shortname, name) values (986, 'NM', 'New Mexico');
insert into states (id, shortname, name) values (987, 'NV', 'Nevada');
insert into states (id, shortname, name) values (988, 'MN', 'Minnesota');
insert into states (id, shortname, name) values (989, 'IL', 'Illinois');
insert into states (id, shortname, name) values (990, 'VA', 'Virginia');
insert into states (id, shortname, name) values (991, 'WI', 'Wisconsin');
insert into states (id, shortname, name) values (992, 'NY', 'New York');
insert into states (id, shortname, name) values (993, 'TX', 'Texas');
insert into states (id, shortname, name) values (994, 'PA', 'Pennsylvania');
insert into states (id, shortname, name) values (995, 'CT', 'Connecticut');
insert into states (id, shortname, name) values (996, 'NC', 'North Carolina');
insert into states (id, shortname, name) values (997, 'MI', 'Michigan');
insert into states (id, shortname, name) values (998, 'MT', 'Montana');
insert into states (id, shortname, name) values (999, 'CA', 'California');
insert into states (id, shortname, name) values (1000, 'WA', 'Washington');
